<?php

use Drupal\Core\Form\FormStateInterface;
use Symfony\Component\HttpFoundation\Request;

/**
 * @file custom_blocks.module
 */

/**
 * Implements hook_theme().
 */
function custom_blocks_theme($existing, $type, $theme, $path) {
  return [
      'businessFrm' => [
        'render element' => 'form'
      ],
      'careerFrm' => [
        'render element' => 'form'
      ],
      'enquiryFrm' => [
        'render element' => 'form'
      ],

  ];
}
